-- MySQL Script generated by MySQL Workbench
-- Fri Apr  9 16:22:25 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema films
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema films
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `films` DEFAULT CHARACTER SET utf8 ;
USE `films` ;

-- -----------------------------------------------------
-- Table `films`.`film_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `films`.`film_types` (
  `film_type_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`film_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `films`.`films`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `films`.`films` (
  `film_id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `year` INT NOT NULL,
  `duration` INT NOT NULL,
  `rating` INT NOT NULL,
  `film_type_id` INT NOT NULL,
  PRIMARY KEY (`film_id`),
  INDEX `fk_films_film_types1_idx` (`film_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_films_film_types1`
    FOREIGN KEY (`film_type_id`)
    REFERENCES `films`.`film_types` (`film_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `films`.`genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `films`.`genres` (
  `genre_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`genre_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `films`.`actors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `films`.`actors` (
  `actor_id` INT NOT NULL AUTO_INCREMENT,
  `surname` VARCHAR(50) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `lastname` VARCHAR(50) NULL,
  `birthdate` DATETIME NULL,
  PRIMARY KEY (`actor_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `films`.`countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `films`.`countries` (
  `country_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`country_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `films`.`films_has_genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `films`.`films_has_genres` (
  `film_id` INT NOT NULL,
  `genre_id` INT NOT NULL,
  PRIMARY KEY (`film_id`, `genre_id`),
  INDEX `fk_films_has_genres_genres1_idx` (`genre_id` ASC) VISIBLE,
  INDEX `fk_films_has_genres_films_idx` (`film_id` ASC) VISIBLE,
  CONSTRAINT `fk_films_has_genres_films`
    FOREIGN KEY (`film_id`)
    REFERENCES `films`.`films` (`film_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_films_has_genres_genres1`
    FOREIGN KEY (`genre_id`)
    REFERENCES `films`.`genres` (`genre_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `films`.`films_has_countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `films`.`films_has_countries` (
  `film_id` INT NOT NULL,
  `country_id` INT NOT NULL,
  PRIMARY KEY (`film_id`, `country_id`),
  INDEX `fk_films_has_countries_countries1_idx` (`country_id` ASC) VISIBLE,
  INDEX `fk_films_has_countries_films1_idx` (`film_id` ASC) VISIBLE,
  CONSTRAINT `fk_films_has_countries_films1`
    FOREIGN KEY (`film_id`)
    REFERENCES `films`.`films` (`film_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_films_has_countries_countries1`
    FOREIGN KEY (`country_id`)
    REFERENCES `films`.`countries` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `films`.`films_has_actors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `films`.`films_has_actors` (
  `film_id` INT NOT NULL,
  `actor_id` INT NOT NULL,
  PRIMARY KEY (`film_id`, `actor_id`),
  INDEX `fk_films_has_actors_actors1_idx` (`actor_id` ASC) VISIBLE,
  INDEX `fk_films_has_actors_films1_idx` (`film_id` ASC) VISIBLE,
  CONSTRAINT `fk_films_has_actors_films1`
    FOREIGN KEY (`film_id`)
    REFERENCES `films`.`films` (`film_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_films_has_actors_actors1`
    FOREIGN KEY (`actor_id`)
    REFERENCES `films`.`actors` (`actor_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
